---
- name: install packages
  sudo: yes
  with_items: liberator_packages
  apt:
    pkg: "{{ item.name }}"
    state: latest

- name: install pip packages
  sudo: yes
  pip:
    requirements: "{{ requirements_path }}"
    executable: pip3

- name: install python2 psycopg
  sudo: yes
  pip:
    name: psycopg2

- name: create liberator DB
  sudo: yes
  sudo_user: postgres
  postgresql_db:
    name: liberator
    encoding: 'UTF-8'
    template: 'template0'

- name: create liberator DB user
  sudo: yes
  sudo_user: postgres
  postgresql_user:
    name: liberator
    password: liberator
    db: liberator
    role_attr_flags: "CREATEDB"

- name: migrate DB
  command: python3 manage.py migrate
  args:
    chdir: "{{ api_path }}"

- name: put api/bin in path
  template:
    src: profile.j2
    dest: ~/.profile
